global.allCollectibles = ds_list_create();
ds_list_add(global.allCollectibles, obj_Food);
ds_list_add(global.allCollectibles, obj_Guitar);
ds_list_add(global.allCollectibles, obj_JewelBox);
ds_list_add(global.allCollectibles, obj_Laptop);
ds_list_add(global.allCollectibles, obj_Suitcase);
ds_list_add(global.allCollectibles, obj_Happygirl);
ds_list_add(global.allCollectibles, obj_Dog);
ds_list_add(global.allCollectibles, obj_Gal);
ds_list_add(global.allCollectibles, obj_Guy);